routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['isLogged'])->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('user', 'UserController');
    Route::resource('auth', 'AuthController');
});
Route::get('/login', 'AuthController@getLogin')->name('login');
Route::post('/login', 'AuthController@postLogin')->name('post.login');
Route::get('/register', 'AuthController@getRegister')->name('register');
Route::post('/register', 'AuthController@postRegister')->name('post.register');
Route::get('/logout', 'AuthController@logout')->name('logout');
Route::get('/linkstorage', function () {
    Artisan::call('storage:link');
});

app/Admin.php
<?php

namespace App;

use Illuminate\Support\Facades\DB;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Admin extends Authenticatable
{
    
    protected $table = 'admins'; 

    protected $fillable = [
        'id', 'username', 'email', 'password'
    
    ];

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\Uuids;

class User extends Authenticatable
{
    use Notifiable, Uuids;

    protected $fillable = [
        'uuid','id', 'fullname', 'username', 'email', 'password',
        'gender', 'age'
    ];
    
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\Http\Requests\AdminRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Ramsey\Uuid\Uuid;

class AuthController extends Controller
{
    public function index()
    {
        return view('auth.login');
    }

    public function getLogin()
    {
        return view('auth.login');
    }

    public function postLogin(Request $request)
    {
        $credentials = array(
            'email' => $request->email,
            'password' => $request->password,
        );

        if (Auth::guard('web')->attempt($credentials)) {
            return redirect('/');
        } else {
            $request->session()->flash('error_login', 'Login Gagal, Cek Kembali Email dan Password');
            return redirect('login');
        }
    }

    public function logout()
    {
        Auth::logout();
        return redirect('login');
    }

    public function getRegister()
    {
        return view('auth.register');
    }

    public function postRegister(Request $request)
    {
        $data = $request->all();
        $data['password'] = bcrypt($request->input("password"));

        Admin::create($data);
        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index() 
    {
        $users = User::all();

        return view('pages.dashboard')->with([
            'users' => $users
        ]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('pages.dashboard');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Validator;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Hash;
use Ramsey\Uuid\Uuid;


class UserController extends Controller
{
    public function index()
    {
        $users = User::all();

        return view('pages.users.index')->with([
            'users' => $users

        ]);
    }

    public function api_store(Request $request)
    {
        $tableName = "users";
        $result = DB::insert(
            'insert into users (id,fullname,username,gender,age,email,password) values (?,?,?,?,?,?,?)',
            [$request->input("id"), $request->input("fullname"), $request->input("username"), $request->input("gender"), $request->input("age"),  $request->input("email"), bcrypt($request->input("password"))]
        );

        return response([
            'message' => 'Data Berhasil Ditambahkan',
            'status' => true,
            'code' => Response::HTTP_CREATED,
            'data' => $result
        ], 201);
    }

    public function create()
    {
        $users = User::all();

        return view('pages.users.create')->with([
            'users' => $users
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->all();
        $data['password'] = Hash::make('password', ['rounds' => 12]);

        User::create($data);
        return redirect()->route('user.index');
    }


    public function show($id)
    {
    }

    public function edit($id)
    {
        $users = User::all();
        $user = User::findOrFail($id);
        return view('pages.users.edit')->with([
            'user' => $user,
            'users' => $users
        ]);
    }

    public function api_update(Request $request, $id)
    {
        $fullname = $request->fullname;
        $username = $request->username;
        $email = $request->email;
        $password = $request->password;
        $gender = $request->gender;
        $age = $request->age;

        $request->getContent();
        $user = User::findOrFail($id);
        if ($fullname !== null) {
            $user->fullname = $fullname;
        }
        if ($username !== null) {
            $user->username = $username;
        }
        if ($email !== null) {
            $user->email = $email;
        }
        if ($password !== null) {
            $user->password = $password;
        }
        if ($gender !== null) {
            $user->gender = $gender;
        }
        if ($age !== null) {
            $user->age = $age;
        }
        $user->save();

        return response([
            'message' => 'Data Berhasil Diedit',
            'status' => 'success',
            'code' => Response::HTTP_OK,
            'data' => $user
        ], 200);
    }

    public function update(Request $request, $id)
    {
        $data = $request->all();

        $user = User::findOrFail($id);
        $user->update($data);

        return redirect()->route('user.index');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('user.index');
    }
}

resources/views/includes/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="ShaynaAdmin - HTML5 Admin Template">
<meta name="viewport" content="width=device-width, initial-scale=1">

resources/views/includes/navbar.blade.php
<!-- Header-->
<header id="header" class="header">
    <div class="top-left">
        <div class="navbar-header">
            <a class="navbar-brand" href="./"><img src="{{asset('images/logo.png')}}" style="width: 30px" alt="Logo"></a>
            <a class="navbar-brand hidden" href="./"><img src="{{asset('images/logo.png')}}" alt="Logo"></a>
            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right">
        <div class="header-menu">
            
            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <img class="user-avatar rounded-circle" src="{{asset('images/admin.jpg')}}" alt="User Avatar">
                </a>
                
                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="{{route('logout')}}"><i class="fa fa-power"></i>Logout</a>
                </div>
            </div>
            
        </div>
    </div>
</header>

resources/views/includes/script.blade.php
<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
{{-- <script src="{{asset('assets/js/main.js'))}}"></script> --}}
<script src="{{asset('assets/js/main.js')}}"></script>

<!--  Chart js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

<!--Chartist Chart-->
<script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
<script src="{{asset('assets/js/init/weather-init.js')}}"></script>

<script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js"></script>
<script src="{{asset('assets/js/init/fullcalendar-init.js')}}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

<!-- Propeller textfield js --> 
<script type="text/javascript" src="dist/js/propeller.min.js"></script>

<!-- Datepicker moment with locales -->
<script type="text/javascript" language="javascript" src="datetimepicker/js/moment-with-locales.js"></script>

<!-- Propeller Bootstrap datetimepicker -->
<script type="text/javascript" language="javascript" src="datetimepicker/js/bootstrap-datetimepicker.js"></script>


<!--Local Stuff-->
<script>
    jQuery(document).ready(function($) {
        "use strict";
        
        $('#interest').select2({
            interest: true,
            multiple: true,
            tokenSeparators: [',']
        });
        
        
        // Pie chart flotPie1
        var piedata = [
        { label: "Pending", data: [[1,32]], color: '#5c6bc0'},
        { label: "Gagal", data: [[1,33]], color: '#ef5350'},
        { label: "Sukses", data: [[1,35]], color: '#66bb6a'}
        ];
        
        $.plot('#flotPie1', piedata, {
            series: {
                pie: {
                    show: true,
                    radius: 1,
                    innerRadius: 0.65,
                    label: {
                        show: true,
                        radius: 2/3,
                        threshold: 1
                    },
                    stroke: {
                        width: 0
                    }
                }
            },
            grid: {
                hoverable: true,
                clickable: true
            }
        });
        // Pie chart flotPie1  End
        // cellPaiChart
        var cellPaiChart = [
        { label: "Direct Sell", data: [[1,65]], color: '#5b83de'},
        { label: "Channel Sell", data: [[1,35]], color: '#00bfa5'}
        ];
        $.plot('#cellPaiChart', cellPaiChart, {
            series: {
                pie: {
                    show: true,
                    stroke: {
                        width: 0
                    }
                }
            },
            legend: {
                show: false
            },grid: {
                hoverable: true,
                clickable: true
            }
            
        });
        // cellPaiChart End
        // Line Chart  #flotLine5
        var newCust = [[0, 3], [1, 5], [2,4], [3, 7], [4, 9], [5, 3], [6, 6], [7, 4], [8, 10]];
        
        var plot = $.plot($('#flotLine5'),[{
            data: newCust,
            label: 'New Data Flow',
            color: '#fff'
        }],
        {
            series: {
                lines: {
                    show: true,
                    lineColor: '#fff',
                    lineWidth: 2
                },
                points: {
                    show: true,
                    fill: true,
                    fillColor: "#ffffff",
                    symbol: "circle",
                    radius: 3
                },
                shadowSize: 0
            },
            points: {
                show: true,
            },
            legend: {
                show: false
            },
            grid: {
                show: false
            }
        });
        // Line Chart  #flotLine5 End
        // Traffic Chart using chartist
        if ($('#traffic-chart').length) {
            var chart = new Chartist.Line('#traffic-chart', {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
                series: [
                [0, 18000, 35000,  25000,  22000,  0],
                [0, 33000, 15000,  20000,  15000,  300],
                [0, 15000, 28000,  15000,  30000,  5000]
                ]
            }, {
                low: 0,
                showArea: true,
                showLine: false,
                showPoint: false,
                fullWidth: true,
                axisX: {
                    showGrid: true
                }
            });
            
            chart.on('draw', function(data) {
                if(data.type === 'line' || data.type === 'area') {
                    data.element.animate({
                        d: {
                            begin: 2000 * data.index,
                            dur: 2000,
                            from: data.path.clone().scale(1, 0).translate(0, data.chartRect.height()).stringify(),
                            to: data.path.clone().stringify(),
                            easing: Chartist.Svg.Easing.easeOutQuint
                        }
                    });
                }
            });
        }
        // Traffic Chart using chartist End
        //Traffic chart chart-js
        if ($('#TrafficChart').length) {
            var ctx = document.getElementById( "TrafficChart" );
            ctx.height = 150;
            var myChart = new Chart( ctx, {
                type: 'line',
                data: {
                    labels: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul" ],
                    datasets: [
                    {
                        label: "Visit",
                        borderColor: "rgba(4, 73, 203,.09)",
                        borderWidth: "1",
                        backgroundColor: "rgba(4, 73, 203,.5)",
                        data: [ 0, 2900, 5000, 3300, 6000, 3250, 0 ]
                    },
                    {
                        label: "Bounce",
                        borderColor: "rgba(245, 23, 66, 0.9)",
                        borderWidth: "1",
                        backgroundColor: "rgba(245, 23, 66,.5)",
                        pointHighlightStroke: "rgba(245, 23, 66,.5)",
                        data: [ 0, 4200, 4500, 1600, 4200, 1500, 4000 ]
                    },
                    {
                        label: "Targeted",
                        borderColor: "rgba(40, 169, 46, 0.9)",
                        borderWidth: "1",
                        backgroundColor: "rgba(40, 169, 46, .5)",
                        pointHighlightStroke: "rgba(40, 169, 46,.5)",
                        data: [1000, 5200, 3600, 2600, 4200, 5300, 0 ]
                    }
                    ]
                },
                options: {
                    responsive: true,
                    tooltips: {
                        mode: 'index',
                        intersect: false
                    },
                    hover: {
                        mode: 'nearest',
                        intersect: true
                    }
                    
                }
            } );
        }
        //Traffic chart chart-js  End
        // Bar Chart #flotBarChart
        $.plot("#flotBarChart", [{
            data: [[0, 18], [2, 8], [4, 5], [6, 13],[8,5], [10,7],[12,4], [14,6],[16,15], [18, 9],[20,17], [22,7],[24,4], [26,9],[28,11]],
            bars: {
                show: true,
                lineWidth: 0,
                fillColor: '#ffffff8a'
            }
        }], {
            grid: {
                show: false
            }
        });
        // Bar Chart #flotBarChart End
    });
    
    $('#mySelect').select2({
        width: '100%',
        placeholder: "Choose Your Interest Topics",
        interest: true,
        multiple: true,
        tokenSeparators: [',']
    });
    
    var oldInterest = $('#interest > option[value={{ Request::old('interest') }}]');
    
    if (oldInterest.length > 0) {
        oldInterest.attr('selected', 'selected');
    }
    
    var s2 = $("#selectEvents").select2({
        placeholder: "Choose event type",
        tags: true
    });
    
    // var vals = ["Trade Fair", "CA", "Party"];
    var vals = [
    {id: 0, title: "Trade Fair"},
    {id: 1, title: "CA"},
    {id: 2, title: "Party"},
    ];
    
    vals.forEach(function(e){
        console.log(e)
        if(!s2.find('option:contains(' + e.title + ')').length) 
        s2.append($(`<option>`).text(e.title));
        });
        
        s2.val(vals).trigger("change"); 
        
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });

        // $('#datetimepicker-default').datetimepicker();
    </script>

resources/views/includes/sidebar.blade.php
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{{route('dashboard')}}"><i class
                        ="menu-icon fa fa-laptop"></i>Dashboard</a>
                    </li>
                    <li class="menu-title">User</li><!-- /.menu-title -->
                    <li class="">
                        <a href={{route('user.index')}}> <i class="menu-icon fa fa-street-view"></i>List User</a>
                    </li>
                    <li class="">
                        <a href="{{route('user.create')}}"> <i class="menu-icon fa fa-plus"></i>Create New User</a>
                    </li>
                </ul>
            </div>
        </nav>
    </aside>

resources/views/includes/style.blade.php
{{-- <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
<link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png"> --}}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
<link rel="stylesheet" href="{{asset('assets/css/cs-skin-elastic.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/style.css')}}">
<!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
<link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />

@import "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css";


<style>
    
    /* Google Material icons */
    @import "http://fonts.googleapis.com/icon?family=Material+Icons";
    
    /* Propeller css */
    @import "dist/css/propeller.min.css";
    
    /* Bootstrap datetimepicker */
    @import "datetimepicker/css/bootstrap-datetimepicker.css";
    
    /* Propeller datetimepicker */
    @import "datetimepicker/css/pmd-datetimepicker.css";
    
    
    #weatherWidget .currentDesc {
        color: #ffffff!important;
    }
    .traffic-chart {
        min-height: 335px;
    }
    #flotPie1  {
        height: 150px;
    }
    #flotPie1 td {
        padding:3px;
    }
    #flotPie1 table {
        top: 20px!important;
        right: -10px!important;
    }
    .chart-container {
        display: table;
        min-width: 270px ;
        text-align: left;
        padding-top: 10px;
        padding-bottom: 10px;
    }
    #flotLine5  {
        height: 105px;
    }
    
    #flotBarChart {
        height: 150px;
    }
    #cellPaiChart{
        height: 160px;
    }
    
</style>

resources/views/layouts/master.blade.php
<!doctype html>
 <html class="no-js" lang="">
<head>
    @include('includes.meta')
    <title>Self Actualization | @yield('title')</title>
    @include('includes.style')
</head>

<body>
    @include('includes.sidebar')
    <div id="right-panel" class="right-panel">
        @include('includes.navbar')
        <div class="content">
            @yield('content')
        </div>
        <div class="clearfix"></div>
    </div>
    @include('includes.script')
</body>
</html>

resources/views/pages/users/create.blade.php
@extends('layouts.master')

@section('title', 'Create User')

@section('content')
<div class="card">
    <div class="card-header">
        <strong>Tambah User</strong>
    </div>
    <div class="card-body card-block">
        <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            {{-- <input type="hidden" name="id" value="id" class="form-control" required/> --}}
            <div class="form-group">
                <label for="fullname" class="form-control-label">Fullname</label>
                <input type="text" name="fullname" value="{{old('fullname')}}" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="email" class="form-control-label">Email</label>
                <input type="email" name="email" value="{{old('email')}}" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="password" class="form-control-label">Password</label>
                <input type="password" name="password" value="{{old('password')}}" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="username" class="form-control-label">Username</label>
                <input type="text" name="username" value="{{old('username')}}" class="form-control" required/>
            </div>
            <div class="form-group">
                <label for="gender" class="form-control-label">Gender</label>
                <select name='gender' class="form-control" required>
                    <option selected disabled value="">Choose Your Gender</option>
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                </select>
            </div>
            <div class="form-group">
                <label for="age" class="form-control-label">Age</label>
                <input type="number" min="15" max="100" name="age" value="{{old('age')}}" class="form-control" required/>
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Tambah User</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/users/edit.blade.php
@extends('layouts.master')

@section('title', 'Create User')

@section('content')
<div class="card">
    <div class="card-header">
        <strong>Ubah User</strong>
    </div>
    <div class="card-body card-block">
        <form action="{{ route('user.update', $user->id) }}" method="POST" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="fullname" class="form-control-label">Fullname</label>
                <input type="text" name="fullname" value="{{old('fullname') ? old('fullname') : $user->fullname}}" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="email" class="form-control-label">Email</label>
                <input type="email" name="email" value="{{old('email') ? old('email') : $user->email}}" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="password" class="form-control-label">Password</label>
                <input type="password" name="password" value="{{old('password')}}" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="username" class="form-control-label">Username</label>
                <input type="text" name="username" value="{{old('username') ? old('username') : $user->username}}" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="gender" class="form-control-label">Gender</label>
                <select name='gender' class="form-control">
                    <option value="male" @if ( $user->gender == 'male') selected="selected" @endif>Male</option>
                    <option value="female" @if ( $user->gender == 'female') selected="selected" @endif>Female</option>
                </select>
            </div>
            
            <div class="form-group">
                <label for="age" class="form-control-label">Age</label>
                <input type="number" min="15" max="100" name="age" value="{{old('age') ? old('age') : $user->age}}" class="form-control"/>
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Ubah User</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/pages/users/index.blade.php
@extends('layouts.master')

@section('title', 'List Users')

@section('content')
<div class="orders">
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="box-title">Daftar User</h4>
            </div>
            <div class="card-body--">
                <div class="table-stats order-table ov-h">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Fullname</th>
                                <th>Username</th>
                                <th>Gender</th>
                                <th>Age</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                @forelse ($users as $user)
                                <td>{{$user->id}}</td>
                                <td>{{$user->fullname}}</td>
                                <td>{{$user->username}}</td>
                                <td>{{$user->gender}}</td>
                                <td>{{$user->age}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    <a href="{{route('user.edit', $user->id)}}" class="btn btn-primary btn-sm">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <form action="{{route('user.destroy', $user->id)}}" method="post" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td collspan="9" class="text-center p-5">
                                        Data tidak tersedia
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection